name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Display environment info
        run: |
          set -x
          python --version
          pip --version
          uname -a
      - name: Install dependencies
        run: |
          set -x
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          set -x
          pytest -vv -o log_cli=true --log-cli-level=DEBUG
